### ISSUE TITLE
[SLPS-02764] Oh No! glitches out in gameplay

### ISSUE THREAD

**Issue by denpakei39** [DKWDRV/DKWDRV#40]
You start out normally, but then the game gets slower while you're inside the house, then the house textures get garbled when you exit the house, and eventually the floor glitches out, causing you to instantly game over.
Ran on scph-77004
https://file.io/GxEvsOxCmuNn

**Comment by DKWDRV** [comment]
@denpakei39 
Fixed 1.7.6
Confirm on your side.

**Comment by denpakei39** [comment]
here's video footage of me playing, the quality is not the best since i got a super cheap capture card
it looks like i can get further, but the same issue still occurs in different places
https://youtu.be/fq-TC70zyrc (the last game over was my fault since i got stuck lol)

**Comment by DKWDRV** [comment]
@denpakei39 have you enabled any special options?
Are you FULLY SURE that the game is defragmented?

**Comment by DKWDRV** [comment]
@denpakei32  try 1.7.6p
